DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS posts;
DROP TABLE IF EXISTS comments;
CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  profile_photo_url TEXT NOT NULL
);
CREATE TABLE posts (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES users(id) NOT NULL,
  photo_url TEXT NOT NULL,
  caption TEXT NOT NULL,
  tags TEXT [] NOT NULL
);
CREATE TABLE comments (
  comment_by BIGINT REFERENCES users(id) NOT NULL,
  post BIGINT REFERENCES post(id) NOT NULL,
  comment TEXT NOT NULL
)